// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsk2okVis5rHVZzC2preRlyZw9vmyaMi8',
    appId: '1:884624927850:web:3655e4e20654aefb942e13',
    messagingSenderId: '884624927850',
    projectId: 'mind-manager-final',
    authDomain: 'mind-manager-final.firebaseapp.com',
    storageBucket: 'mind-manager-final.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCI_qXvHVzuO5nWGozuerZuXz5lBgZg4u0',
    appId: '1:884624927850:android:e548efc962b03982942e13',
    messagingSenderId: '884624927850',
    projectId: 'mind-manager-final',
    storageBucket: 'mind-manager-final.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAC6tsmuo085w8oBlFSykYz2H4xs-l7H6w',
    appId: '1:884624927850:ios:126472d5b6f2b75a942e13',
    messagingSenderId: '884624927850',
    projectId: 'mind-manager-final',
    storageBucket: 'mind-manager-final.firebasestorage.app',
    iosBundleId: 'com.example.mindManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAC6tsmuo085w8oBlFSykYz2H4xs-l7H6w',
    appId: '1:884624927850:ios:126472d5b6f2b75a942e13',
    messagingSenderId: '884624927850',
    projectId: 'mind-manager-final',
    storageBucket: 'mind-manager-final.firebasestorage.app',
    iosBundleId: 'com.example.mindManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsk2okVis5rHVZzC2preRlyZw9vmyaMi8',
    appId: '1:884624927850:web:4ede19b0c164fdbc942e13',
    messagingSenderId: '884624927850',
    projectId: 'mind-manager-final',
    authDomain: 'mind-manager-final.firebaseapp.com',
    storageBucket: 'mind-manager-final.firebasestorage.app',
  );
}
